server:
  context-path: /gpsolutions/
  port: 8000
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: App
  messages:
    basename: messages/messages
    encoding: UTF-8
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root

logging:
  path: ./log