server:
  context-path: /gpsolutions/
  port: 8000
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: App
  messages:
    basename: messages/messages
    encoding: UTF-8
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root

logging:
  path: ./log

swagger: "2.0"
info:
  description: "Interact with example"
  version: "V1.1.0"
  title: "The example API"
  termsOfService: "http://example.com"
  contact:
    name: "André Schild"
    url: "http://example.com"
    email: "a.schild@aarboard.ch"
  license:
    name: "example License"
    url: "http://example.com/"